name: API Deployment
on: 
  push:
    branches:
      - main
    secrets:
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}

env:
  region: us-east-1
  TEST_VAR: prod_test

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-key-id: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: us-east-1

      - name: Deploy
        run: npm run sls config credentials -- --overwrite --provider aws --key ${{ secrets.ACCESS_KEY }} --secret ${{ secrets.SECRET_KEY }} && npm run deploy:ci