name: API Deployment
on: 
  push:
    branches:
      - main

env:
  region: us-east-1
  ENV: prod

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git
        uses: actions/checkout@v3
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install dependencies
        run: npm ci --production

      - name: Run tests
        run: npm run test:ci

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-key-id: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: us-east-1

      - name: Deploy
        run: npm run deploy:ci